vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_thumbnail:
            uri_prefix: /post/thumbnail
            upload_destination: '%kernel.project_dir%/public/upload/post_thumbnail'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post_translation_section_media:
            uri_prefix: /post/translation_section
            upload_destination: '%kernel.project_dir%/public/upload/post_translation_section'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
