vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_media:
            uri_prefix: /post/media
            upload_destination: '%kernel.project_dir%/public/upload/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        post_section_media:
            uri_prefix: /post-section/media
            upload_destination: '%kernel.project_dir%/public/upload/post_section'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        category_media:
            uri_prefix: /category/media
            upload_destination: '%kernel.project_dir%/public/upload/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
