vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_media:
            uri_prefix: /upload/post
            upload_destination: '%kernel.project_dir%/public/upload/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
        post_section_media:
            uri_prefix: /upload/post_section
            upload_destination: '%kernel.project_dir%/public/upload/post_section'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
        category_media:
            uri_prefix: /upload/category
            upload_destination: '%kernel.project_dir%/public/upload/category'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
