vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        post_thumbnail:
            uri_prefix: /images/post/thumbnail
            upload_destination: '%kernel.project_dir%/public/upload/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
