# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
  
  redis:
    # Production Redis configuration
    # Consider adding Redis persistence with AOF for production
    command: redis-server --appendonly yes --appendfsync everysec
