# Development environment override
services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./var:/app/var
    environment:
      SERVER_NAME: ${SERVER_NAME:-local.tinie-bakerie.com}, php:80
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-debug,coverage}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> meilisearch/search-bundle ###
  meilisearch:
    ports:
      - "7700"
###< meilisearch/search-bundle ###

###> symfony/messenger ###
  messenger-worker:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - ./var:/app/var
###< symfony/messenger ###
