apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinie-bakerie-secrets
  namespace: tinie-bakerie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: tinie-bakerie-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: APP_SECRET
