apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: tinie-bakerie-db
  namespace: tinie-bakerie
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  bootstrap:
    initdb:
      database: app
      owner: app
  storage:
    size: 1Gi
    storageClass: local-path
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
