apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: tinie-bakerie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
