apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical
  namespace: tinie-bakerie
spec:
  provider:
    infisical:
      hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            key: accessToken
            name: infisical-machine-identity
      secretsScope:
        projectSlug: tinie-bakerie-y0e9
        environmentSlug: staging
        secretsPath: /
